on:
  issues:
    types:
      - labeled
      - edited

permissions:
  contents: write
  issues: write


jobs:
  issue_to_markdown:
    name: Collect all issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: eunjae-lee/issue-to-markdown@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # New files are located at `<project-root>/<dest>/<slug or issue_number>/index.md`. (default: 'content')
          dest: 'content'

          # (default: '.md')
          extension: '.md'

          # If set to `true`, the `slug` from the frontmatter of the issue body will be used as the folder name instead of `issue_number`. If set to `false`, only `issue_number` is used. (default: true)
          slug_as_folder_name: true

          # Key for the slug from the frontmatter. This is used only when `slug_as_folder_name` is `true`. (`slug` by default.)
          slug_key: 'slug'

      # By default, `publish` label is required for the workflow to work.
      #label: 'publish'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'collect issues'
